spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/authcore}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER:authcore}
spring.datasource.password=${POSTGRES_PASSWORD:authcore}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
