spring.application.name=AuthCore
server.port=8080

spring.datasource.url=jdbc:h2:mem:jwt_api;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true

app.jwt.secret=V7l3Z4qB6uS8yC2dE9gH1jK5mN7pQ3rT6vW8xY0zA2bC4dE6fG8hI0jK2lM4nO6p
app.jwt.expiration=2h
